### ISSUE TITLE
Spopupfy background is broken after newest spotify ui update

### ISSUE THREAD

**Issue by atlidev** [anghelos/spopupfy#2]
![image](https://user-images.githubusercontent.com/33323908/236844226-6d4f550e-33a3-4aad-bfd5-01e67cfa5f33.png)

The background gradient has disappeared after the latest spotify UI update. See image above.

**Comment by anghelos** [comment]
Thanks for letting me know, I haven't been in front of my computer much lately! I'll try to fix it when I get the chance.

**Comment by anghelos** [comment]
It should be fixed in the newly uploaded version (0.4.6.1). It should be rolled out by Firefox in the next day or so.
